### ISSUE TITLE
Java to Kotlin and ButterKnife to Viewbinding Migration

### ISSUE THREAD

**Issue by Aditya-gupta99** [openMF/android-client#1968]
- [x] SplashScreen Activity : #1969
 - [x] Authentication Activity : #1970 
 - [x] HomeActivity : #1981  
 - [x] MifosBase classes : #1984 
 - [x] Individual Collection Sheet Migration : #1986 
 - [x] Collection Sheet Migration : #1989 
 - [x] Datamanager : #1988 
 - [x] Data Class Migration : #1988 
 - [x] All Activities, Fragments and Adapter Viewbinding migration : #1990 , #1991 
 - [ ] All Activities, Fragments and Classes Java to Kotlin migration : #1993 , #1994 , #1995 , #1996

**Comment by Ashutoshgupta22** [comment]
I have already created an issue for Butterknife to viewBinding migration #1927 and have opened a PR
